### ISSUE TITLE
Use a different character to delimit tags/values when encoded as a string

### ISSUE THREAD

**Issue by tillberg** [appoptics/appoptics-api-go#10]
@akahn pointed out that colons are legal characters in tag keys and values, and so we should use something other than "::" to delimit them when encoding as a string (in https://github.com/librato/appoptics-go/blob/master/tags.go), as a tag key or value that includes "::" would not be decoded correctly.

**Comment by trevrosen** [comment]
Alter to use a null byte literal `\x00` as the separator
