### ISSUE TITLE
Interface for TaggedMeasurementSet + MeasurementSet

### ISSUE THREAD

**Issue by ysamlan** [appoptics/appoptics-api-go#61]
Is there a practical way to use `TaggedMeasurementSet` for RuntimeMetrics right now? If there was an interface that both `MeasurementSet` and `TaggedMeasurementSet` conformed to, and all those methods that accepted `MeasurementSet` only today accepted that interface instead, you'd get the flexibility to use TaggedMeasurementSets for that (plus you could use them directly in `Reporter`). I ended up having to copy-paste the entire `runtime.go` file and apply `MetricWithTags` to each call myself to get tagged runtime metrics. 

I'd add extracting the `MeasurementSet` out of the `TaggedMeasurementSet` so that I can pass it to `Reporter` feels icky -- you have to know that the tags are applied at measurement time, not at upload time, for that to make sense, which ought to just be an implementation detail.

**Comment by trevrosen** [comment]
Hi @ysamlan thanks for the issue. Let me take a look and get back with you ASAP.

**Comment by trevrosen** [comment]
I've found some time to take a look and:

1. No there's not a way to do that in the code now as far as I know
2. Converting this to take a common interface shouldn't be difficult, and I believe that this is something we can look at doing as we move toward `1.0` release for this client.

We're working to reconcile several different approaches to persisting metrics as part of taking it to `1.0.`. We appreciate your patience in the meantime. 😄

**Comment by trevrosen** [comment]
Closing in favor of using the Go metrics lib
